### ISSUE TITLE
UpnpService fails trying to create stream client

### ISSUE THREAD

**Issue by ijabz** [jupnp/jupnp#144]
Background:Trying to write an Audio Control Point the code was able to find media servers but not media renderers, so I then tried using the jupnp vesion of the lib instead, but my first problem is that starting up the uPnpService fails

```
UpnpService upnpService = new UpnpServiceImpl(new DefaultUpnpServiceConfiguration());
upnpService.startup();
```

fails with 

```
Exception in thread "main" java.lang.NullPointerException
	at org.jupnp.transport.impl.jetty.JettyTransportConfiguration.createStreamClient(JettyTransportConfiguration.java:26)
	at org.jupnp.DefaultUpnpServiceConfiguration.createStreamClient(DefaultUpnpServiceConfiguration.java:178)
	at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:135)
	at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:258)
```

**Comment by ijabz** [comment]
Error was introduced in https://github.com/4thline/cling/commit/146579c1e953881a4621fd277fb491d3b066aedb

Workaround for me to was to create pwn version of DefaultUpnpServiceConfiguration and add
```

@Override
    @SuppressWarnings("rawtypes")
    public StreamClient createStreamClient() {
        return transportConfiguration.createStreamClient(getSyncProtocolExecutorService(), createStreamClientConfiguration());
    }

    private StreamClientConfiguration createStreamClientConfiguration() {
        return new StreamClientConfigurationImpl(defaultExecutorService, timeoutSeconds, 5, retryAfterSeconds, retryIterations);
    }
```

**Comment by Dani-Hub** [comment]
This issue prevents us from using the versions 2.6.0 and 2.6.1 of jupnp. We reverted back to 2.5.2 as a fix.
