### ISSUE TITLE
IllegalArgumentException: Invalid URI host: null (authority: :30080)

### ISSUE THREAD

**Issue by wborn** [jupnp/jupnp#159]
It seems that jupnp 2.7.1 still tries to retrieve data based on invalid URIs even with https://github.com/jupnp/jupnp/pull/142.

See: https://community.openhab.org/t/java-exception-upnp-async-after-upgrade-from-4-0-3-to-4-1-0/152728

```
Exception in thread "upnp-async-11" java.lang.IllegalArgumentException: Invalid URI host: null (authority: :30080)
        at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:541)
        at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:526)
        at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:484)
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl.createRequest(JettyStreamClientImpl.java:113)
        at org.jupnp.transport.impl.jetty.JettyStreamClientImpl.createRequest(JettyStreamClientImpl.java:1)
        at org.jupnp.transport.spi.AbstractStreamClient.sendRequest(AbstractStreamClient.java:87)
        at org.jupnp.transport.RouterImpl.send(RouterImpl.java:327)
        at org.jupnp.protocol.RetrieveRemoteDescriptors.describeService(RetrieveRemoteDescriptors.java:325)
        at org.jupnp.protocol.RetrieveRemoteDescriptors.describeServices(RetrieveRemoteDescriptors.java:263)
        at org.jupnp.protocol.RetrieveRemoteDescriptors.describe(RetrieveRemoteDescriptors.java:205)
        at org.jupnp.protocol.RetrieveRemoteDescriptors.describe(RetrieveRemoteDescriptors.java:184)
        at org.jupnp.protocol.RetrieveRemoteDescriptors.run(RetrieveRemoteDescriptors.java:104)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Looks like in this case the URI is not null but is invalid because it has no hostname and only a port.

**Comment by wborn** [comment]
I don't think #142 ever fixed the issue because I was able to reproduce it with some of the URIs in the test.
