### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by einstein-m2011** [jupnp/jupnp#17]
Hi,

I followed the instructions in the Docs (StartingApp.xhtml), I could compile the files (using javac) but I couldn't start the server or client. The error appears as follows:

```
fev 04, 2015 5:52:48 PM org.jupnp.DefaultUpnpServiceConfiguration$JUPnPExecutor afterExecute

Thread terminated org.jupnp.registry.LocalItems$4@d42cbc abruptly with exception: java.lang.RuntimeException: Fatal error
while executing protocol 'SendingNotificationAlive': java.lang.NullPointerException
fev 04, 2015 5:52:48 PM org.jupnp.DefaultUpnpServiceConfiguration$JUPnPExecutor afterExecute

Root cause: java.lang.NullPointerException
Exception in thread "jupnp-2" java.lang.RuntimeException: Fatal error while executing protocol 'SendingNotificationAlive': java.lang.Nu
llPointerException
        at org.jupnp.protocol.SendingAsync.run(SendingAsync.java:59)
        at org.jupnp.registry.LocalItems$4.run(LocalItems.java:297)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at org.jupnp.protocol.async.SendingNotification.execute(SendingNotification.java:62)
        at org.jupnp.protocol.async.SendingNotificationAlive.execute(SendingNotificationAlive.java:40)
        at org.jupnp.protocol.SendingAsync.run(SendingAsync.java:53)
        ... 4 more
```

Did I forgot something? Some library?

**Comment by kaikreuzer** [comment]
NPE definitely sounds like a bug. Feel free to analyze yourself what causes it and to suggest a fix.

**Comment by einstein-m2011** [comment]
OK!

**Comment by kaikreuzer** [comment]
I haven't seen this NPE ever, so I close this issue due to inactivity.
