### ISSUE TITLE
NoSuchMethodError with Javalin 6

### ISSUE THREAD

**Issue by realOxy** [jupnp/jupnp#218]
Versions:
- jupnp: 2.7.1
- javax-servlet-api: 3.1.0
- jetty(server, servlet, client): 9.3.14.v20161028

All work, but after I use another dependency [Javalin 6.0.0](https://github.com/javalin/javalin), got the message again:

```
java.lang.NoSuchMethodError: No direct method <init>(Ljavax/servlet/Servlet;)V in class Lorg/eclipse/jetty/servlet/ServletHolder; or its super classes (declaration of 'org.eclipse.jetty.servlet.ServletHolder' appears in /data/app/com.m3u.androidApp-RDbJyQppCSLm1KV1z_Yydw==/base.apk!classes26.dex)
                                                                                                    	at org.jupnp.transport.impl.jetty.JettyServletContainer.registerServlet(JettyServletContainer.java:80)
                                                                                                    	at org.jupnp.transport.impl.ServletStreamServerImpl.init(ServletStreamServerImpl.java:73)
                                                                                                    	at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:422)
                                                                                                    	at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:125)
```

~~Looks like the jupnp used the jetty whose version is defined by javalin.~~

When click Jetty source code(JettyServletContainer.java:80), Android Studio told me:

```
library source does not match the bytecode for class "ServletHolder".
```

Then click show diff:
> There are many different lines.
<img width="1434" alt="image" src="https://github.com/jupnp/jupnp/assets/70512220/7dd8484f-46ea-4512-bc61-a1f080ea1d4a">

How can I solve the problem?

Example: 
https://github.com/realOxy/M3UAndroid/blob/e94f827622d15eaf435df48b6567463d6ec300bc/dlna/build.gradle.kts#L42-L47
https://github.com/realOxy/M3UAndroid/blob/e94f827622d15eaf435df48b6567463d6ec300bc/data/build.gradle.kts#L82

**Comment by wborn** [comment]
I don't think it will work as Javalin 6 seems to use Jetty 11 (jakarta.servlet) and jUPnP uses Jetty 9 (javax.servlet). Maybe it will work if they upgrade to Jetty 12 which supports both namespaces.

See also:

* https://github.com/javalin/javalin/issues/2067
* https://github.com/jupnp/jupnp/issues/204
