### ISSUE TITLE
InputStream readAllBytes In Android device error 

### ISSUE THREAD

**Issue by FlWppFly** [jupnp/jupnp#226]
Run jupnp on Android device , i got the InputStream readAllBytes error

```
2024-03-08 15:35:45.929  5622-5622  GraphicsEnvironment     com.qytech.qylauncher                V  ANGLE Developer option for 'com.qytech.qylauncher' set to: 'default'
2024-03-08 15:35:45.930  5622-5622  GraphicsEnvironment     com.qytech.qylauncher                V  ANGLE GameManagerService for com.qytech.qylauncher: false
2024-03-08 15:35:45.931  5622-5622  GraphicsEnvironment     com.qytech.qylauncher                V  Neither updatable production driver nor prerelease driver is supported.
2024-03-08 15:35:45.936  5622-5622  NetworkSecurityConfig   com.qytech.qylauncher                D  No Network Security Config specified, using platform default
2024-03-08 15:35:45.939  5622-5622  NetworkSecurityConfig   com.qytech.qylauncher                D  No Network Security Config specified, using platform default
2024-03-08 15:35:46.133  5622-5649  ContextImpl             com.qytech.qylauncher                W  Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1912 android.content.ContextWrapper.bindService:812 com.qytech.dlna.DLNACastManager.bindCastService:62 com.qytech.qylauncher.QYApplication$onCreate$1.invokeSuspend:19 kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith:33 
2024-03-08 15:35:47.606  5622-5622  tech.qylaunche          com.qytech.qylauncher                W  Class androidx.compose.runtime.snapshots.SnapshotStateList failed lock verification and will run slower.
                                                                                                    Common causes for lock verification issues are non-optimized dex code
                                                                                                    and incorrect proguard optimizations.
2024-03-08 15:35:48.495  5622-5622  RenderThread            com.qytech.qylauncher                I  type=1400 audit(0.0:822): avc: denied { open } for path="/dev/__properties__/u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20173 scontext=u:r:system_app:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=1
2024-03-08 15:35:48.495  5622-5622  RenderThread            com.qytech.qylauncher                I  type=1400 audit(0.0:823): avc: denied { getattr } for path="/dev/__properties__/u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20173 scontext=u:r:system_app:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=1
2024-03-08 15:35:48.495  5622-5622  RenderThread            com.qytech.qylauncher                I  type=1400 audit(0.0:824): avc: denied { map } for path="/dev/__properties__/u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20173 scontext=u:r:system_app:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=1
2024-03-08 15:35:48.499  5622-5652  mali_so                 com.qytech.qylauncher                I  [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 1356; [Func] : base_context_deal_with_version_affairs_rk_ext;
                                                                                                    arm_release_ver of this mali_so is 'g7p1-01bet0', rk_so_ver is '7@0 '.
2024-03-08 15:35:48.499  5622-5652  mali_so                 com.qytech.qylauncher                I  [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 1372; [Func] : base_context_deal_with_version_affairs_rk_ext;
                                                                                                    arm_release_vers are match. to set the full mali_ver 'g7p1-01bet0-x-7@0' as value of 'sys.gmali.version'.
2024-03-08 15:35:48.506  5622-5652  hw-ProcessState         com.qytech.qylauncher                D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2024-03-08 15:35:48.642  5622-5652  hw-ProcessState         com.qytech.qylauncher                D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2024-03-08 15:35:48.712  5622-5638  OpenGLRenderer          com.qytech.qylauncher                I  Davey! duration=2726ms; Flags=1, FrameTimelineVsyncId=7306, IntendedVsync=22931861289906, Vsync=22932311289888, InputEventId=0, HandleInputStart=22932319909313, AnimationStart=22932319922730, PerformTraversalsStart=22932320339813, DrawStart=22934464692904, FrameDeadline=22931877956572, FrameInterval=22932319786522, FrameStartTime=16666666, SyncQueued=22934508587575, SyncStart=22934508719700, IssueDrawCommandsStart=22934509587700, SwapBuffers=22934584052541, FrameCompleted=22934587553416, DequeueBufferDuration=31209, QueueBufferDuration=1128750, GpuCompleted=22934587553416, SwapBuffersCompleted=22934586409208, DisplayPresentTime=0, 
2024-03-08 15:35:48.967  5622-5622  Choreographer           com.qytech.qylauncher                I  Skipped 142 frames!  The application may be doing too much work on its main thread.
2024-03-08 15:35:49.032  5622-5622  DLNACastManager         com.qytech.qylauncher                I  onServiceConnected: [com.qytech.dlna.DLNACastService]
2024-03-08 15:35:49.120  5622-5622  ActivityThread          com.qytech.qylauncher                W  ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
2024-03-08 15:35:49.315  5622-5622  System.err              com.qytech.qylauncher                W  Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
2024-03-08 15:35:49.850  5622-5622  Choreographer           com.qytech.qylauncher                I  Skipped 51 frames!  The application may be doing too much work on its main thread.
2024-03-08 15:35:49.862  5622-5622  QYApplication$onCreate  com.qytech.qylauncher                D  DLNACastManager onDeviceAdded urn:schemas-upnp-org:device:MediaServer:1 (LocalDevice) Identity: (DeviceIdentity) UDN: uuid:a3801c00-7122-4cb3-8b55-2ccf83497f80, Root: true
2024-03-08 15:35:50.931  5622-5633  tech.qylaunche          com.qytech.qylauncher                I  Background concurrent copying GC freed 125872(6323KB) AllocSpace objects, 8(160KB) LOS objects, 49% free, 8021KB/15MB, paused 310us,425us total 301.565ms
2024-03-08 15:35:51.201  5622-5622  QYApplication$onCreate  com.qytech.qylauncher                D  DLNACastManager onDeviceAdded urn:schemas-upnp-org:device:MediaServer:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:e5744a58-b20e-4533-8399-7aa55c7617b0, Descriptor: http://192.168.0.171:2869/upnphost/udhisapi.dll?content=uuid:e5744a58-b20e-4533-8399-7aa55c7617b0, Root: true
2024-03-08 15:35:51.427  5622-5622  QYApplication$onCreate  com.qytech.qylauncher                D  DLNACastManager onDeviceAdded urn:schemas-upnp-org:device:MediaRenderer:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:05184a07-b2d9-42e7-ad3b-0b9a7733fa56, Descriptor: http://192.168.0.171:2869/upnphost/udhisapi.dll?content=uuid:05184a07-b2d9-42e7-ad3b-0b9a7733fa56, Root: true
2024-03-08 15:35:51.865  5622-5622  QYApplication$onCreate  com.qytech.qylauncher                D  DLNACastManager onDeviceAdded urn:schemas-upnp-org:device:MediaRenderer:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:800a805c23dc-dmr, Descriptor: http://192.168.0.77:1962/description.xml, Root: true
2024-03-08 15:35:52.007  5622-5704  ProfileInstaller        com.qytech.qylauncher                D  Installing profile for com.qytech.qylauncher
2024-03-08 15:35:52.673  5622-5622  QYApplication$onCreate  com.qytech.qylauncher                D  DLNACastManager onDeviceAdded urn:schemas-upnp-org:device:MediaRenderer:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:fe7ca012-cfe8-7e5e-eb24-7b5a6c6f26e2, Descriptor: http://192.168.0.97:1919/, Root: true
2024-03-08 15:35:55.398  5622-5688  AndroidRuntime          com.qytech.qylauncher                E  FATAL EXCEPTION: jupnp-6
                                                                                                    Process: com.qytech.qylauncher, PID: 5622
                                                                                                    java.lang.NoSuchMethodError: No virtual method readAllBytes()[B in class Ljava/io/InputStream; or its super classes (declaration of 'java.io.InputStream' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at org.jupnp.transport.impl.ServletUpnpStream.readRequestMessage(ServletUpnpStream.java:132)
                                                                                                    	at org.jupnp.transport.impl.ServletUpnpStream.run(ServletUpnpStream.java:60)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
2024-03-08 15:35:55.449  5622-5688  Process                 com.qytech.qylauncher                I  Sending signal. PID: 5622 SIG: 9
---------------------------- PROCESS ENDED (5622) for package com.qytech.qylauncher ----------------------------

```
I try fix this code ，and build jar and import to Android studio , so we can fix the readAllBytes compatible Android

**Comment by wborn** [comment]
Try updating your API level to 33 or newer, see:

https://developer.android.com/reference/java/io/InputStream#readAllBytes()
