### ISSUE TITLE
Issue with starting upnp service

### ISSUE THREAD

**Issue by Khaleel432** [jupnp/jupnp#234]
I'm getting an error: Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/Servlet, I don't have any other dependencies and I'm using intellij. This is my first attempt at creating a UPNP applicaiton so please let me know if I've configured something wrong. The program crashes during the upnp startup procedure and I'm not sure how to proceed.

Code is below.
```
private boolean forwardPorts() {
        int port = 25565;
        System.out.println("Attempting to open port " + 25565 + " with UPNP");
        UpnpService upnp = new UpnpServiceImpl( new DefaultUpnpServiceConfiguration());
        upnp.startup();
        ControlPoint controlPoint = upnp.getControlPoint();

        if(controlPoint != null) {
            controlPoint.search(new STAllHeader());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
            System.out.println("Search complete: ");
            System.out.println(upnp.getRegistry().getRemoteDevices());
            upnp.getRegistry().getRemoteDevices().forEach((remoteDevice -> {
                System.out.println(remoteDevice.getDisplayString());
            }));
        }
        else {
            System.out.println("Control point is null, unable to execute search function");
        }

        return false;
    }
```
Full error:
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/Servlet
	at org.jupnp.transport.impl.jetty.JettyTransportConfiguration.createStreamServer(JettyTransportConfiguration.java:48)
	at org.jupnp.DefaultUpnpServiceConfiguration.createStreamServer(DefaultUpnpServiceConfiguration.java:189)
	at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:397)
	at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:127)
	at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:263)
	at org.openports.MainWindow.forwardPorts(MainWindow.java:166)
	at org.openports.MainWindow.createWindow(MainWindow.java:68)
	at org.openports.MainWindow.<init>(MainWindow.java:59)
	at org.openports.Main.main(Main.java:5)
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 9 more

**Comment by wborn** [comment]
You can probably fix it by adding a few dependencies, see https://github.com/jupnp/jupnp/issues/157.
