### ISSUE TITLE
Error parsing PossiblePlaybackStorageMedia values like "CD-DA"

### ISSUE THREAD

**Issue by haku** [jupnp/jupnp#246]
I have been seen traces in logs that include:
```
Caused by: java.lang.IllegalArgumentException: No enum constant org.jupnp.support.model.StorageMedium.CD-DA
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.jupnp.support.model.StorageMedium.valueOf(StorageMedium.java:27)
	at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.enumValueOf(AVTransportVariable.java:136)
	at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.enumValueOf(AVTransportVariable.java:123)
	at org.jupnp.support.lastchange.EventedValueEnumArray.valueOf(EventedValueEnumArray.java:39)
	at org.jupnp.support.lastchange.EventedValueEnumArray.valueOf(EventedValueEnumArray.java:27)
	at org.jupnp.support.lastchange.EventedValue.valueOf(EventedValue.java:60)
	at org.jupnp.support.lastchange.EventedValue.<init>(EventedValue.java:38)
	at org.jupnp.support.lastchange.EventedValueEnumArray.<init>(EventedValueEnumArray.java:34)
	at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.<init>(AVTransportVariable.java:129)
	at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossiblePlaybackStorageMedia.<init>(AVTransportVariable.java:148)
```

I think this is caused by `AVTransportVariable` calling `StorageMedium.valueOf("CD-DA")` which fails because the enum entry is `CD_DA`.  Instead it should be calling `StorageMedium.valueOrVendorSpecificOf()` or similar.

Not sure how much impact this has beyond logspam, but the dropped events could cause some devices to update as expected etc.

**Comment by haku** [comment]
in the same are of the code, i am also seeing:
```
Caused by: java.lang.NullPointerException: null
        at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.enumValueOf(AVTransportVariable.java:135)
        at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.enumValueOf(AVTransportVariable.java:123)
        at org.jupnp.support.lastchange.EventedValueEnumArray.valueOf(EventedValueEnumArray.java:39)
        at org.jupnp.support.lastchange.EventedValueEnumArray.valueOf(EventedValueEnumArray.java:27)
        at org.jupnp.support.lastchange.EventedValue.valueOf(EventedValue.java:60)
        at org.jupnp.support.lastchange.EventedValue.<init>(EventedValue.java:38)
        at org.jupnp.support.lastchange.EventedValueEnumArray.<init>(EventedValueEnumArray.java:34)
        at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossibleRecordStorageMedia.<init>(AVTransportVariable.java:129)
        at org.jupnp.support.avtransport.lastchange.AVTransportVariable$PossiblePlaybackStorageMedia.<init>(AVTransportVariable.java:148)
```

Which looks like it is caused by trying to iterate over an null array.
PossibleRecordStorageMedia and PossibleRecordQualityModes both have this issue but CurrentTransportActions looks like it has been fixed previously.

**Comment by wborn** [comment]
> Instead it should be calling StorageMedium.valueOrVendorSpecificOf() or similar.

I would think so too! Maybe you can create a PR to fix it?
