### ISSUE TITLE
DMR cannot be discovered by other devices

### ISSUE THREAD

**Issue by EternalSoySauce** [jupnp/jupnp#250]
I create a Media Render Receiver local device, but it cannot be discovered by other dms server. 
But keep all the code unchanged and switch the dependency library to cling, then my dmr can be discovered.
The only difference in the code is that cling does not have `upnpService.startup()`. 
Is there something wrong with my code or is there a bug in jupnp library?

Here's my service code
```
class DLNARendererService : AndroidUpnpServiceImpl() {

    companion object {
        private const val LOCAL_DEVICE_NAME = "My custom name"
    }

    private val logger = Logger.getLogger(DLNARendererService::class.java)
    private val serviceBinder = RendererServiceBinderWrapper()
    private var localDevice: LocalDevice? = null

    override fun onCreate() {
        super.onCreate()
        try {
            upnpService.startup()
            localDevice = createRendererDevice()
            upnpService.registry.addDevice(localDevice)
            logger.i("onCreate Success")
        } catch (e: Exception) {
            e.printStackTrace()
            logger.i("onCreate failed")
            stopSelf()
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int = START_STICKY

    override fun onBind(intent: Intent): IBinder = serviceBinder

    override fun onDestroy() {
        localDevice?.let { upnpService.registry.removeDevice(it) }
        super.onDestroy()
        logger.i("onDestroy")
    }

    @Throws(ValidationException::class, IOException::class)
    private fun createRendererDevice(): LocalDevice {
        val info = "my custom device info"
        val udn = UDN(UUID.nameUUIDFromBytes(info.toByteArray()))
        val officialWebsiteUrl = "my url"

        val identity = DeviceIdentity(udn)
        val deviceType = UDADeviceType("MediaRenderer", 1)
        val deviceDetails = DeviceDetails(
            "my friendly name",
            ManufacturerDetails("my Manufacturer", officialWebsiteUrl),
            ModelDetails("my model name", "my description", "1.0", officialWebsiteUrl),
            arrayOf(DLNADoc("DMR", DLNADoc.Version.V1_5)),
            null
        )
        val icons = emptyArray<Icon>()
        val localServices = generateLocalServices()

        return LocalDevice(identity, deviceType, deviceDetails, icons, localServices)
    }

    private fun generateLocalServices(): Array<LocalService<*>> {
        val serviceBinder = AnnotationLocalServiceBinder()

        // AV Transport Service
        val avTransportService = serviceBinder.read(AVTransportService::class.java) as LocalService<AVTransportService>
        avTransportService.manager = object : LastChangeAwareServiceManager<AVTransportService>(avTransportService, AVTransportLastChangeParser()) {
            override fun createServiceInstance(): AVTransportService {
                return AVTransportService()
            }
        }

        // Render Service
        val renderingControlService = serviceBinder.read(AudioRenderingControlService::class.java) as LocalService<AudioRenderingControlService>
        renderingControlService.manager = object : LastChangeAwareServiceManager<AudioRenderingControlService>(renderingControlService, RenderingControlLastChangeParser()) {
            override fun createServiceInstance(): AudioRenderingControlService {
                return AudioRenderingControlService(MyApplication.getInstance())
            }
        }

        return arrayOf(avTransportService, renderingControlService)
    }

    protected inner class RendererServiceBinderWrapper : AndroidUpnpServiceImpl.Binder(), RendererServiceBinder {
        override val service: DLNARendererService
            get() = this@DLNARendererService
    }

}

interface RendererServiceBinder {
    val service: DLNARendererService
}
```

Here's my gradle:
```
    implementation 'org.jupnp:org.jupnp:3.0.2'
    implementation 'org.jupnp:org.jupnp.support:3.0.2'
    implementation 'org.jupnp:org.jupnp.android:3.0.2'
    implementation 'org.eclipse.jetty:jetty-server:9.4.56.v20240826'
    implementation 'org.eclipse.jetty:jetty-servlet:9.4.56.v20240826'
    implementation 'org.eclipse.jetty:jetty-client:9.4.56.v20240826'
```

**Comment by EternalSoySauce** [comment]
It seems to be related to the jetty version.
Which version of `javax.servlet` and `jetty` should I use with `jupnp:3.0.2`?

**Comment by EternalSoySauce** [comment]
Use old cling version then all will be ok.  But change cling version from 2.1.1 to 2.1.2 also cannot discover dmr. 
What's wrong with the new version?
```
    // Cling library required
    api 'org.fourthline.cling:cling-core:2.1.1'
    api 'org.fourthline.cling:cling-support:2.1.1'
    // Servlet
    api 'javax.servlet:javax.servlet-api:3.1.0'
    // Jetty
    api 'org.eclipse.jetty:jetty-server:8.1.21.v20160908'
    api 'org.eclipse.jetty:jetty-servlet:8.1.21.v20160908'
    api 'org.eclipse.jetty:jetty-client:8.1.21.v20160908'
```

**Comment by wborn** [comment]
If I run something similar based on your code the following exception is thrown:

```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in path at index 2: my url
	at java.base/java.net.URI.create(URI.java:883)
	at org.jupnp.model.meta.ManufacturerDetails.<init>(ManufacturerDetails.java:48)
	at org.jupnp.Main.createRendererDevice(Main.java:91)
	at org.jupnp.Main.main(Main.java:69)
Caused by: java.net.URISyntaxException: Illegal character in path at index 2: my url
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 3 more
```

So try using a valid URI instead of `my url` in your `val officialWebsiteUrl = "my url"` statement.

After updating that I can make the local device renderer in the jUPnP registry also show up as renderer in [BubbleUPnP](https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp).

You can also see that a device is properly registered if you count the number of local devices via `upnpService.getRegistry().getLocalDevices().size()`.

Without a proper URI it won't get added to the local devices.

**Comment by EternalSoySauce** [comment]
The name and url in the project code are both real and valid parameters, but I changed them to something vague like "my url" when I posted the code here.

**Comment by wborn** [comment]
Try setting a breakpoint in `getLocalDevices()`: 

https://github.com/jupnp/jupnp/blob/6820b8a7dd4c67c17ce0a88d4490d8b8b1900eb2/bundles/org.jupnp/src/main/java/org/jupnp/registry/RegistryImpl.java#L329

You'll then see if it gets there, what devices there are and what it does with them when it handles a search request in `ReceivingSearch`.

**Comment by g-wellsa** [comment]
Third-party players and those developed based on older versions cannot be searched, meaning that the new version has departed from the original protocol principles, is a new set of frameworks, and the value has been lost

**Comment by Greatwallcorner** [comment]
I has similar problems 
![图片](https://github.com/user-attachments/assets/2a24453a-a0ff-4106-8d38-bc08f4e94436)
![图片](https://github.com/user-attachments/assets/9531e9b2-7233-41a7-b560-a5f8b514a6c9)
this is my code: https://github.com/Greatwallcorner/TV-Multiplatform/tree/main/composeApp/src/commonMain/kotlin/com/corner/dlna
![图片](https://github.com/user-attachments/assets/3091820f-5872-4337-ae9e-213d9f7a5d5e)

**Comment by g-wellsa** [comment]
> I has similar problems ![图片](https://private-user-images.githubusercontent.com/49832311/395769587-2a24453a-a0ff-4106-8d38-bc08f4e94436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk1ODctMmEyNDQ1M2EtYTBmZi00MTA2LThkMzgtYmMwOGY0ZTk0NDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NTAxOGE3Yzc3MTYxOTUxNWEzMjBhZDU3NjRhNmFiZDM0ODFjMzBlZGM5M2YwMjk0ZjA1NWM1NDdiN2MwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3MHE39dWyU-cwP-64c08lVwbnZxCEs5P4iQ8rLHtSDQ) ![图片](https://private-user-images.githubusercontent.com/49832311/395769621-9531e9b2-7233-41a7-b560-a5f8b514a6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk2MjEtOTUzMWU5YjItNzIzMy00MWE3LWI1NjAtYTVmOGI1MTRhNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzFjNzIyYzA4NTdlYTdkYzdmMDVkY2Q5YTM3MDY5Yjk0OTMzMmE0OTBlZDBiYTIyMWQzMWRkOGZiYTQ5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wZiOJlnIJV9SvhvgDOHe0GBu4oJneeOrcNzz9l7N4sQ) this is my code: https://github.com/Greatwallcorner/TV-Multiplatform/tree/main/composeApp/src/commonMain/kotlin/com/corner/dlna ![图片](https://private-user-images.githubusercontent.com/49832311/395769932-3091820f-5872-4337-ae9e-213d9f7a5d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk5MzItMzA5MTgyMGYtNTg3Mi00MzM3LWFlOWUtMjEzZDlmN2E1ZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmI5ZmJiYTlhNzdkMWM2ODNhMTA1YjA2YmQ0ODAwODAyMWQzMDlhNDZlZjQyZGZhOTE4NWI0MmIyZjM0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6jwCj8LQsCJ-SgQ3m-O6Y3x0yCgxB1M7hr6-Ym2jRvQ)

hello, have you solved this problem yet?

**Comment by Greatwallcorner** [comment]
> > I has similar problems ![图片](https://private-user-images.githubusercontent.com/49832311/395769587-2a24453a-a0ff-4106-8d38-bc08f4e94436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk1ODctMmEyNDQ1M2EtYTBmZi00MTA2LThkMzgtYmMwOGY0ZTk0NDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NTAxOGE3Yzc3MTYxOTUxNWEzMjBhZDU3NjRhNmFiZDM0ODFjMzBlZGM5M2YwMjk0ZjA1NWM1NDdiN2MwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3MHE39dWyU-cwP-64c08lVwbnZxCEs5P4iQ8rLHtSDQ) ![图片](https://private-user-images.githubusercontent.com/49832311/395769621-9531e9b2-7233-41a7-b560-a5f8b514a6c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk2MjEtOTUzMWU5YjItNzIzMy00MWE3LWI1NjAtYTVmOGI1MTRhNmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMzFjNzIyYzA4NTdlYTdkYzdmMDVkY2Q5YTM3MDY5Yjk0OTMzMmE0OTBlZDBiYTIyMWQzMWRkOGZiYTQ5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wZiOJlnIJV9SvhvgDOHe0GBu4oJneeOrcNzz9l7N4sQ) this is my code: https://github.com/Greatwallcorner/TV-Multiplatform/tree/main/composeApp/src/commonMain/kotlin/com/corner/dlna ![图片](https://private-user-images.githubusercontent.com/49832311/395769932-3091820f-5872-4337-ae9e-213d9f7a5d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM4OTcsIm5iZiI6MTczNDMzMzU5NywicGF0aCI6Ii80OTgzMjMxMS8zOTU3Njk5MzItMzA5MTgyMGYtNTg3Mi00MzM3LWFlOWUtMjEzZDlmN2E1ZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmI5ZmJiYTlhNzdkMWM2ODNhMTA1YjA2YmQ0ODAwODAyMWQzMDlhNDZlZjQyZGZhOTE4NWI0MmIyZjM0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6jwCj8LQsCJ-SgQ3m-O6Y3x0yCgxB1M7hr6-Ym2jRvQ)
> 
> hello, have you solved this problem yet?

not yet

**Comment by lixingmao** [comment]
Encountered the same issue in an Android project, DMR developed using cling in the old version could be smoothly discovered by third-party players, but after switching to jupnp in the new version, it could not be searched for. Combined with the log analysis of the versions, no result was obtained.
Can @wborn assist in identifying which related changes might have caused this issue, provide relevant suspected points, or offer a process for analyzing related logs?

**Comment by wborn** [comment]
If you can make a small example app having the issue I can have a look.

**Comment by Greatwallcorner** [comment]
> If you can make a smal
[JupnpTest.zip](https://github.com/user-attachments/files/18435646/JupnpTest.zip)
l example app having the issue I can have a look.

here is, can you hava a look

**Comment by wborn** [comment]
I still have this on my to-do list to see if I can reproduce it. 😉
