### ISSUE TITLE
Multicast listeners to IPv6 even though IPv6 is supposed to be excluded

### ISSUE THREAD

**Issue by haku** [jupnp/jupnp#252]
I was getting confused at why some devices were appearing / disappearing seemingly randomly.
Some debugging later i found:

```
D1030 13:13:39.099 [   t-upnp1] o.j.t.s.MulticastReceiver UDP datagram received from: fe80:0:0:0:cacb:b8ff:fec8:e63c%2:59448 on local interface: enp2s0 and address: 192.168.1.6
E1030 13:13:42.418 [  t-upnp68] o.j.t.impl.DatagramIOImpl   Details: datagram.socketAddress=/fe80:0:0:0:cacb:b8ff:fec8:e63c%2:59448, length=330, offset=0, data.bytes=330
E1030 13:13:42.418 [  t-upnp68] o.j.t.impl.DatagramIOImpl   Details: socket=java.net.MulticastSocket@5f8bcef5, closed=false, bound=true, inetAddress=null, remoteSocketAddress=null, networkInterface=name:0.0.0.0
E1030 13:13:42.418 [  t-upnp68] o.j.t.impl.DatagramIOImpl Exception sending datagram to: /fe80:0:0:0:cacb:b8ff:fec8:e63c%2
java.io.IOException: Address family not supported by protocol
	at java.base/java.net.PlainDatagramSocketImpl.send0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.send(AbstractPlainDatagramSocketImpl.java:155)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at org.jupnp.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:162)
	at org.jupnp.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:154)
	at org.jupnp.transport.RouterImpl.send(RouterImpl.java:298)
	at org.jupnp.protocol.async.ReceivingSearch.sendSearchResponseAll(ReceivingSearch.java:200)
	at org.jupnp.protocol.async.ReceivingSearch.sendResponses(ReceivingSearch.java:139)
	at org.jupnp.protocol.async.ReceivingSearch.execute(ReceivingSearch.java:106)
	at org.jupnp.protocol.ReceivingAsync.run(ReceivingAsync.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The issue appears to be here: https://github.com/jupnp/jupnp/blob/b876d866929ff7ff0f90de5e40457922f6c16be6/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/MulticastReceiverImpl.java#L83
Calling `new InetSocketAddress(int)` uses `InetAddress.anyLocalAddress()` to pick an address for the interface, so depending on iteration order it might be a v4 or v6 address.
I have a rough fix on this branch: https://github.com/haku/jupnp/tree/IPv6Binding
I guessed a bunch on how to find the correct address to bind to, so i appreciate feedback and corrections.  Thanks!

**Comment by haku** [comment]
after more digging, most of what i wrote above is wrong >.<
i misunderstood `anyLocalAddress()`, which actually returns 0.0.0.0 or ::0.
the actual issue seems to be that Java binds `udp6` (not `udp`) even for IPv4 addresses.
for example:

```
InetAddress address = InetAddress.getByName("0.0.0.0");
System.out.println(address.getClass());  // "class java.net.Inet4Address"
MulticastSocket socket = new MulticastSocket(new InetSocketAddress(address, 1900));
```
```
$ netstat -lnup
udp6       0      0 :::1900                 :::*                                107630/java
```
so even though an Inet4Address is used, it will still receive any IPv6 packets sent to that interface.
and packets sent to the IPv6 address of the interface using `ncat` are received.

this was tested using Java 11 on Ubuntu 22.04.

**Comment by haku** [comment]
i have also seen log messages like:
```
T1030 15:58:47.467 [   t-upnp1] NetworkAddressFactoryImpl Could not find local bind address in same subnet as: fe80:0:0:0:cacb:b8ff:fec8:e63c%2
```
which come from here: https://github.com/jupnp/jupnp/blob/b876d866929ff7ff0f90de5e40457922f6c16be6/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/NetworkAddressFactoryImpl.java#L247-L268
interestingly, when this happens `isIPv6` is false.

but even then, if sending to a v6 address is not supported (stacktrace in first comment), there is no way to reply to a msg from a v6 address.
i am not sure what the practical implications of this are, i think it mostly relates to discovering devices on localhost only?
and if there is no way to force MulticastSocket to use the IPv4 stack with Java code, then the only practical work-around is `-Djava.net.preferIPv4Stack=true`, as ugly as that is.

sorry if i have not been much help here, thank you for following along my debugging.

**Comment by wborn** [comment]
It think you can also use the `org.jupnp.network.useInterfaces` and `org.jupnp.network.useAddresses` system properties to limit which interfaces and addresses are used, see: 

https://github.com/jupnp/jupnp/blob/6820b8a7dd4c67c17ce0a88d4490d8b8b1900eb2/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/NetworkAddressFactoryImpl.java#L85-L96

**Comment by tentechtop** [comment]
Could you provide a use case? For example, if my port is 8800, how can I use this project to make my port accessible from the outside network?
